// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using NmapMaui.Data;

#nullable disable

namespace NmapMaui.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524161132_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NmapMaui.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Category").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("CreatedBy").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Details").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Level").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("Timestamp").HasColumnType("datetime2");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("NmapMaui.Models.Base64", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Input").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Output").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsEncode").HasColumnType("bit");
                    b.Property<DateTime>("Date").HasColumnType("datetime2");
                    b.Property<string>("CreatedBy").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.ToTable("Base64s");
                });

            modelBuilder.Entity("NmapMaui.Models.Dns", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hostname").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("IpAddress").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("Date").HasColumnType("datetime2");
                    b.Property<string>("CreatedBy").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.ToTable("DnsLookups");
                });

            modelBuilder.Entity("NmapMaui.Models.Encryption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Input").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Output").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsEncrypt").HasColumnType("bit");
                    b.Property<DateTime>("Date").HasColumnType("datetime2");
                    b.Property<string>("CreatedBy").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.ToTable("Encryptions");
                });

            modelBuilder.Entity("NmapMaui.Models.Gobuster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Target").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Wordlist").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Result").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("Date").HasColumnType("datetime2");
                    b.Property<string>("CreatedBy").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.ToTable("GobusterRuns");
                });

            modelBuilder.Entity("NmapMaui.Models.Hash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Input").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Algorithm").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Output").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("Date").HasColumnType("datetime2");
                    b.Property<string>("CreatedBy").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.ToTable("Hashes");
                });

            modelBuilder.Entity("NmapMaui.Models.Netcat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Host").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("Port").HasColumnType("int");
                    b.Property<string>("Result").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("Date").HasColumnType("datetime2");
                    b.Property<string>("CreatedBy").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.ToTable("NetcatRuns");
                });

            modelBuilder.Entity("NmapMaui.Models.Nmap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NmapPort").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("Date").HasColumnType("datetime2");
                    b.Property<string>("CreatedBy").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.ToTable("NmapResults");
                });

            modelBuilder.Entity("NmapMaui.Models.PassGen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Input").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Output").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("Date").HasColumnType("datetime2");
                    b.Property<string>("CreatedBy").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.ToTable("PassGens");
                });

            modelBuilder.Entity("NmapMaui.Models.PassStr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Input").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Output").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Result").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("Date").HasColumnType("datetime2");
                    b.Property<string>("CreatedBy").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.ToTable("PassStrs");
                });

            modelBuilder.Entity("NmapMaui.Models.Ping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Input").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("Date").HasColumnType("datetime2");
                    b.Property<string>("CreatedBy").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.ToTable("Pings");
                });

            modelBuilder.Entity("NmapMaui.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Username").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("PasswordHash").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime?>("LastLoginAt").HasColumnType("datetime2");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.HasKey("Id");
                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
